name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to web server
        run: |
          # Add host key to known hosts
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
          # Deploy files using rsync (more efficient than scp for updates)
          rsync -avz --delete \
            --exclude '.git/' \
            --exclude '.github/' \
            --exclude '.gitignore' \
            --exclude '.env' \
            --exclude 'deploy.ps1' \
            --exclude 'README.md' \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.REMOTE_DIR }}/
